//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x1_Proto_levelBuild_Orsha_N_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x1_Proto_levelBuild_Orsha_N_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x1_Proto_levelBuild_Orsha_N_LD_1v1_DEST {
            get {
                object obj = ResourceManager.GetObject("_2x1_Proto_levelBuild_Orsha_N_LD_1v1_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Foret_Tsel_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Foret_Tsel_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Kostritsa_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Kostritsa_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Kostritsa_LD_1v1_DEST {
            get {
                object obj = ResourceManager.GetObject("_2x2_Kostritsa_LD_1v1_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Lacs_Sianno_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Lacs_Sianno_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Lacs_Sianno_LD_1v1_DEST {
            get {
                object obj = ResourceManager.GetObject("_2x2_Lacs_Sianno_LD_1v1_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Lenina_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Lenina_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Ostrowno_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Ostrowno_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Ostrowno_LD_1v1_DEST {
            get {
                object obj = ResourceManager.GetObject("_2x2_Ostrowno_LD_1v1_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Plateau_Central_Orsha_E_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Plateau_Central_Orsha_E_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_River_Swamp_Krupa_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_River_Swamp_Krupa_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Shchedrin_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Shchedrin_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Slutsk_E_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Slutsk_E_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Slutsk_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Slutsk_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Slutsk_W_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Slutsk_W_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Urban_River_Bobr_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Urban_River_Bobr_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x2_Ville_Centrale_Haroshaje_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_2x2_Ville_Centrale_Haroshaje_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x3_Oarba_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_2x3_Oarba_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2x3_Oarba_LD_2v2_DEST {
            get {
                object obj = ResourceManager.GetObject("_2x3_Oarba_LD_2v2_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _321 {
            get {
                object obj = ResourceManager.GetObject("321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Astrouna_Novka_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Astrouna_Novka_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Beshankovichy_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Beshankovichy_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Bridges_Smolyany_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Bridges_Smolyany_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_East_Vitebsk_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_East_Vitebsk_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_East_Vitebsk_LD_2v2_DEST {
            get {
                object obj = ResourceManager.GetObject("_3x2_East_Vitebsk_LD_2v2_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Highway_LD {
            get {
                object obj = ResourceManager.GetObject("_3x2_Highway_LD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Ilomantsi_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Ilomantsi_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Ilomantsi_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Ilomantsi_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Island_Losnica_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Island_Losnica_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Lenina_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Lenina_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Lenina_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Lenina_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Lipen_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Lipen_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Lyakhavichy_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Lyakhavichy_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Lyakhavichy_LD_3v3_DEST {
            get {
                object obj = ResourceManager.GetObject("_3x2_Lyakhavichy_LD_3v3_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Marecages_Naratch_lake_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Marecages_Naratch_lake_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Mogilev_LD_10v10 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Mogilev_LD_10v10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Mogilev_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Mogilev_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Ostrowno_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Ostrowno_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Ostrowno_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Ostrowno_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Rivers_Pleshchenitsy_S_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Rivers_Pleshchenitsy_S_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Shchedrin_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Shchedrin_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Shchedrin_LD_2v2_DEST {
            get {
                object obj = ResourceManager.GetObject("_3x2_Shchedrin_LD_2v2_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Shchedrin_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Shchedrin_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Siedlce_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Siedlce_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Siedlce_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Siedlce_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Slutsk_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Slutsk_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Slutsk_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Slutsk_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Tali_Ihantala_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Tali_Ihantala_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Tali_Ihantala_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Tali_Ihantala_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Tali_Ihantala_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Tali_Ihantala_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Urban_roads_Krupki_LD_10v10 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Urban_roads_Krupki_LD_10v10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Urban_roads_Krupki_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Urban_roads_Krupki_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Veselovo_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Veselovo_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_West_Bobrujsk_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_West_Bobrujsk_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_West_Bobrujsk_LD_2v2_DEST {
            get {
                object obj = ResourceManager.GetObject("_3x2_West_Bobrujsk_LD_2v2_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_West_Brest_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_3x2_West_Brest_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_West_Brest_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_West_Brest_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_West_Brest_LD_3v3 {
            get {
                object obj = ResourceManager.GetObject("_3x2_West_Brest_LD_3v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_West_Brest_LD_3v3_DEST {
            get {
                object obj = ResourceManager.GetObject("_3x2_West_Brest_LD_3v3_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Zbuczyn_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Zbuczyn_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3x2_Zbuczyn_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_3x2_Zbuczyn_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4x2_Lenina_LD_4v4 {
            get {
                object obj = ResourceManager.GetObject("_4x2_Lenina_LD_4v4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4x2_Ostrowno_LD_4v4 {
            get {
                object obj = ResourceManager.GetObject("_4x2_Ostrowno_LD_4v4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4x2_Shchedrin_LD_4v4 {
            get {
                object obj = ResourceManager.GetObject("_4x2_Shchedrin_LD_4v4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4x2_Slutsk_LD_4v4 {
            get {
                object obj = ResourceManager.GetObject("_4x2_Slutsk_LD_4v4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4x2_Slutsk_LD_4v4_DEST {
            get {
                object obj = ResourceManager.GetObject("_4x2_Slutsk_LD_4v4_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4x2_tannenberg_10vs10 {
            get {
                object obj = ResourceManager.GetObject("_4x2_tannenberg_10vs10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4x2_Tannenberg_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_4x2_Tannenberg_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4x2_Tannenberg_LD_2v2 {
            get {
                object obj = ResourceManager.GetObject("_4x2_Tannenberg_LD_2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4x2_Vistula_Gora_Kalwaria_LD_1v1 {
            get {
                object obj = ResourceManager.GetObject("_4x2_Vistula_Gora_Kalwaria_LD_1v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4x2_Vistula_Gora_Kalwaria_LD_4v4 {
            get {
                object obj = ResourceManager.GetObject("_4x2_Vistula_Gora_Kalwaria_LD_4v4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4x2_Vistula_Gora_Kalwaria_LD_4v4_DEST {
            get {
                object obj = ResourceManager.GetObject("_4x2_Vistula_Gora_Kalwaria_LD_4v4_DEST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
